version: '3.8'
services:
    edgedb:
        image: edgedb/edgedb
        # environment:
        #   EDGEDB_SERVER_SECURITY: insecure_dev_mode
        #   EDGEDB_SERVER_ADMIN_UI: enabled
        volumes:
            - ./edgedb_data:/var/lib/edgedb/data
            - ./dbschema:/dbschema
        ports:
            - 5656:5656
        env_file: ./.env

    resume:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
            - /app/node_modules
        env_file: ./.env
        ports:
            - 5173:5173
        depends_on:
            - edgedb

            